#!/bin/bash

echo "This will locally log into redhat registry, you will be required to create an account first if you haven't already."
echo "Then your credential store will be linked from docker to kubernetes so its able to pull images from redhat registry."

# https://github.com/docker/for-mac/issues/4100#issuecomment-593957408
sed -i '' '/credsStore/d' ${HOME}/.docker/config.json

docker login registry.redhat.io 

kubectl create secret generic redhat-repo-creds \
    --from-file=.dockerconfigjson=${HOME}/.docker/config.json \
    --type=kubernetes.io/dockerconfigjson